version: '3.8'
services:
  ohdsipredictiontutorial:
    image: ohdsi/ohdsipredictiontutorial:1.0.0
    build:
      context: .
      args:
        APP_NAME: OhdsiPredictionTutorial
    ports:
      - "3838:3838"
